version: "3"
services:
  web:
    build: .  # Dockerfile sẽ được sử dụng từ thư mục hiện tại
    image: shinc07/web-test-docker:latest
    ports:
      - "8000:8080"
    volumes:
      - .:/usr/src/app  # Liên kết thư mục hiện tại với thư mục trong container
    environment:
      - DJANGO_SETTINGS_MODULE=PythonWeb.settings  # Ví dụ về biến môi trường, có thể điều chỉnh theo ứng dụng của bạn
    networks:
      - webnet

networks:
  webnet:
    driver: bridge  # Tạo mạng cầu nối để các service có thể giao tiếp với nhau